#!/usr/bin/env bash

# heroku will override $PS1 when specified as a config var, so we'll set it here to make the jupyter
# terminal interface a little prettier:
export PS1='\[\033[01;34m\]\w\[\033[00m\]\$'


echo "Creating app for proxy server..."
python3 create_proxy.py
echo "Proxy server app created"

echo "Starting Jupyterhub..."
exec jupyterhub --debug